### ISSUE TITLE
MySQL compatibility

### ISSUE THREAD

**Issue by Dev-Laurin** [joegasewicz/Flask-File-Upload#32]
sqlalchemy is giving me: 

VARCHAR requires a length on dialect mysql

I'm assuming it is as simple as adding a length when connecting to flask sql alchemy. Could you please put this in a release soon?

**Comment by joegasewicz** [comment]
Hi @Dev-Laurin for sure, hopefully this will be today or tomorrow,
thanks, Joe.

**Comment by joegasewicz** [comment]
My guess is that where we define the Column we are not assigning a string length:
https://github.com/joegasewicz/Flask-File-Upload/blob/1a0a33fe2069bb2813f209b426c207843480cfcd/flask_file_upload/_model_utils.py#L79

Ill update this so the user can pass in a string length which will be available on `v0.0.8`

If you can let me know if that fixes the issue i would be grateful.

**Comment by Dev-Laurin** [comment]
Thank you!

**Comment by joegasewicz** [comment]
Closing this issue as I have submitted the above fix.. @Dev-Laurin let me know if you experience any further issues. Just be aware that these later version require the `db` now to be passed directly to `FileUpload()`... thank you.
