### ISSUE TITLE
Saving Uploaded Image to Server

### ISSUE THREAD

**Issue by Dev-Laurin** [joegasewicz/Flask-File-Upload#45]
Hello again, you fixed compatibility with MySQL - thanks! 

However I am having a new problem. I believe I'm almost to a fully working solution with this last hurdle. The error I'm getting is: 

INFO in routes: [FLASK_FILE_UPLOAD_ERROR]: Couldn't create file path: /static/uploads/device/9/binder.png

My configuration is: 
UPLOAD_FOLDER = '/static/uploads'
ALLOWED_EXTENSIONS = ["jpg", "png"]
MAX_CONTENT_LENGTH = 1000 * 1000 * 1024 * 1024 

In my models.py: 
```
@file_upload.Model
class Device(db.Model):
    image = file_upload.Column(db)
```

In my routes.py: 
```
image = request.files["image"]
device = file_upload.save_files(device, files={
	"image": image
})
```

__init__.py: 
```
db = SQLAlchemy()
file_upload = FileUpload(db=db)

def create_app():
	#create and configure the app 
	app = Flask(__name__, instance_relative_config=True, 
		template_folder="templates", static_folder="static")
	app.config.from_envvar('APP_CONFIG_FILE')

	db.init_app(app)
	file_upload.init_app(app)	
```

**Comment by Dev-Laurin** [comment]
Nevermind, silly me! I got it to work by following the docs for the UPLOAD_FOLDER configuration. Aka I changed it to: 

`UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.realpath(__file__)), "../smartify/static/uploads") `

**Comment by joegasewicz** [comment]
thank you @Dev-Laurin  👍
